// Angular/startingProjectAngular/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  private reactDescriptions = ['Fundamental', 'Crucial', 'Core'];

  private genRandomInt(max: number) {
    return Math.floor(Math.random() * (max + 1));
  }

  public Description = this.reactDescriptions[this.genRandomInt(2)];
  imgReact = '../assets/react-core-concepts.png';

}

<header>
    <img src="../assets/react-core-concepts.png" alt="Stylized atom" />
    <h1>React Essentials</h1>
    <p>
      Fundamental Angular concepts you will need for almost any app you are
      going to build!
    </p>
  </header>

// React/01-starting-project/src/Header.jsx

import reactImg from './assets/react-core-concepts.png'
const reactDescriptions = ['Fundamental', 'Crucial', 'Core'];

function genRandomInt(max) {
  return Math.floor(Math.random() * (max + 1));
}

export default function Header() {
  const description = reactDescriptions[genRandomInt(2)];
  return (
    <header>
      <img src={reactImg} alt="Stylized atom" />
      <h1>React Essentials</h1>
      <p>
        {description} React concepts you will need for almost any app you are
        going to build!
      </p>
    </header>
  );
}
