// React/01-starting-project/src/App.jsx
function Header()
{
  return (
    <header>
    <img src="src/assets/react-core-concepts.png" alt="Stylized atom" />
    <h1>React Essentials</h1>
    <p>
      Fundamental React concepts you will need for almost any app you are
      going to build!
    </p>
  </header>
  );
}



function App() {
  return (
    <div>
     <Header/>
      <main>
        <h2>Time to get started!</h2>
      </main>
    </div>
  );
}

export default App;

// Angular/startingProjectAngular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'startingProjectAngular';
}

<div>
  <header>
    <img src="./assets/react-core-concepts.png" alt="Stylized atom" />
    <h1>React Essentials</h1>
    <p>
      Fundamental Angular concepts you will need for almost any app you are
      going to build!
    </p>
  </header>
  <main>
    <h2>Time to get started!</h2>
  </main>
</div>
<router-outlet></router-outlet>
